Document: gateway
Title: Debian gateway Manual
Author: <insert document author here>
Abstract: This manual describes what gateway is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gateway/gateway.sgml.gz

Format: postscript
Files: /usr/share/doc/gateway/gateway.ps.gz

Format: text
Files: /usr/share/doc/gateway/gateway.text.gz

Format: HTML
Index: /usr/share/doc/gateway/html/index.html
Files: /usr/share/doc/gateway/html/*.html
